name: weather_app
description: Weather app


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.0.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - images/
    - Icons/

  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Regular.otf
        - asset: fonts/Metropolis-Light.otf
        - asset: fonts/Metropolis-Black.otf
        - asset: fonts/Metropolis-Thin.otf
        - asset: fonts/Metropolis-SemiBold.otf
        - asset: fonts/Metropolis-Medium.otf


